[workspace]
[package]
name = "school-mangment-suite"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
defer = "0.2.1"
dotenv = "0.15"
register = {path = "register" }
